### ISSUE TITLE
or

### ISSUE THREAD

**Issue by yawnt** [rsdoiel/sqlish#16]
ideas for `VAR='value' OR VAR='other'`

```
.where({ var: { $eq: ['value','other'] }})

.where({ var: { $in: ['value','other'] }})
```

i like n 2 better.. i can work on that tomorrow if you like it.. lemme know

//yawn

**Comment by rsdoiel** [comment]
Yes, I like both.  variable compared to an array I assume would be combined with an OR.

```
.where({ var: { $eq: ['value','other'] }})   ==> (var = "value") OR (var = "other")
```

Please feel free to implement $in if you get a chance. I'm changing how the SQL is rendered in toString() so that we can
have predictable order for assembling. This is important for SQLite since changing the order of AUTO_INCREMENT PRIMARY KEY can be the difference between working and not working as expected.

Feel free to branch or fork as needed. Thanks R.

**Comment by yawnt** [comment]
okay i'll do that tomorrow

i'm also going to make it recursive

eg

```
$or: { {$like: /lol/}, {$like: /asd/}} // var like ... or like..
```

does that make sense or do you want to keep it simpler?

**Comment by rsdoiel** [comment]
Recursion is fine (as along as their is a stop condition ;-). I know this sounds weird but I actually think it can lead to more readable code in some cases.

**Comment by yawnt** [comment]
we can close this one right? $or does what i wanted for $in, no need to duplicate... it only creates confusion

**Comment by rsdoiel** [comment]
I think we can close it. Thanks.
